name: simplyfind
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  mvc_pattern: ^3.0.0
  google_maps_flutter: ^0.5.21+8
  flutter_launcher_icons : ^0.7.4
  permission_handler: '^4.0.0'
  location: ^2.3.5
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/start.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/back-arrow.png
    - assets/images/logout.png
    - assets/images/man.png
    - assets/images/network.png
    - assets/images/pin.png
    - assets/images/restaurant.png
    - assets/images/speech.png
    - assets/images/student.png
    - assets/images/wc.png
    - assets/images/start.png
    - assets/images/left.png
    - assets/images/checkIn.png
    - assets/data/eventDataBase.json
    - assets/data/connectionsDataBase.json
    - assets/data/auxiliarPOIDataBase.json
